### ISSUE TITLE
Dark Mode not working for some cards with non-default themes

### ISSUE THREAD

**Issue by Santobert** [home-assistant/frontend#10923]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The dark mode filter doesn't work when a non-default theme is chosen as dark theme. Map cards are also affected.

### Describe the behavior you expected

Map colors are inverted when dark mode is active. Even when a non-default theme is selected as dark mode.

### Steps to reproduce the issue

1. Install a theme (e.g. midnight)
2. Select the freshly installed theme as backend selected theme for dark mode
![Screenshot_20211214-224533](https://user-images.githubusercontent.com/15657682/146084398-d771aa43-d88e-48fb-8c48-c8783dd94701.png)
3. Configure a map card or use the `dark_mode_filter` property
4. Enable dark theme in mobile app settings
5. Enjoy :tad

### What version of Home Assistant Core has the issue?

2021.12.1

### What was the last working version of Home Assistant Core?

2021.9

### In which browser are you experiencing the issue with?

Chrome and Firefox

### Which operating system are you using to run this browser?

Android and Linux

### Problem-relevant frontend configuration

Map card:
```yaml
entities:
  - entity: person.a
  - entity: person.b
hours_to_show: 48
type: map
```

Picture elements

```yaml
elements:
  - entity: sensor.openweathermap_temperature
    style:
      left: 0.4in
      top: 0.4in
    type: state-label
  - entity: sensor.openweathermap_humidity
    style:
      left: 0.4in
      top: 0.6in
    type: state-label
...
image: /local/pictures/grundriss_farbe.png
entity: binary_sensor.anwesenheit
state_filter:
  'off': grayscale(100%)
dark_mode_filter: invert(100%)
type: picture-elements
```

### Additional information

Issue #10178 describes a similar issue. Both issues appeared with the same update.

**Comment by spacegaier** [comment]
Please add the config for the map card into the issue template ("Problem-relevant frontend configuration").

**Comment by Santobert** [comment]
> Please add the config for the map card into the issue template ("Problem-relevant frontend configuration").

Done. Even though it's pretty standard

**Comment by VelocityMaximus** [comment]
I have the same issue here with a picture elements card in panel mode.

![image](https://user-images.githubusercontent.com/50678949/146672065-684e204b-b664-4535-8c97-8ec7eedfa2ca.png)

The template is backend selected but want to override it in the card itself.  Before version 2021.12.x it worked well. Now (2021.12.3) it does not change the text and icon colors and keeps the system wide template colors like the other cards.

This is how it looks like when the backend changed to a dark theme (AMOLED Blue from JuanMTech):

![image](https://user-images.githubusercontent.com/50678949/146672325-07c82ca9-b699-4e71-958e-d1e6f3a849ff.png)

**Comment by idoaflalo** [comment]
I have the same problem.

**Comment by VelocityMaximus** [comment]
Another update about backend selected templates:

I do not have a screenshot of it but will describe what happens:
When I let an automation switch from theme the cards are not updated well.
For example: if a tile is white and it switches to another template (which has black background), some tiles are changed to the right color. 
Switching to different tabs does not update the tiles. Only refreshing the page works.
When the theme is changed again, the tiles have the same behavior and then I need to refresh the page to fix the colors.

**Comment by VelocityMaximus** [comment]
I figured out where the textcolor is inherited from:

![image](https://user-images.githubusercontent.com/50678949/147740039-4edc5ff1-abf6-4a32-800b-4a9b673edd01.png)

I have updated from 2021.12.4 to the latest (20221.12.7) and still the same issue.

The view keeps the backend selected theme instead of the overrule option of the view.

**Comment by carldunham** [comment]
Not stale. Not fixed. Still a pain.
