### ISSUE TITLE
Zone editor map not working

### ISSUE THREAD

**Issue by Skeletorjus** [home-assistant/frontend#12261]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I add a new zone from the zone editor, I get the popup, but I'm not able to do anything with the map (add marker, change radius) except scrolling. This does not update the coordinates.
If I click on a zone that I've already created in the UI, the section of the map shows my home zone with no markers. The only way to add or edit a zone is to manually put the latitude, longitude, and radius in the editor and click save.
Might not be related, but when I save or update a zone, this error is shown:
`Cannot read properties of undefined (reading 'enable')`

The map in the zone editor is a weird size as well:
![image](https://user-images.githubusercontent.com/9031934/162434004-13ee07e0-e99b-4069-a2af-b681b86f8310.png)
(scrolled to a random location as it always default my home zone)

The button to add zone from current location of a person entity seems also to be gone.

All the zones are working as they should in automations and shows up fine on the regular map.
Have tried deleting all zones and re-adding them with no luck.

### Describe the behavior you expected

I expected it to work. It has been working in the past, unsure when it broke for me.

### Steps to reproduce the issue

1. Go to zone editor
2. Try to add, edit or click on a zone

### What version of Home Assistant Core has the issue?

core-2022.4.1

### In which browser are you experiencing the issue with?

Google Chrome 100.0.4896.75, Firefox 99.0 (64-bit), Android app

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
Tried with and without zone: in configuration.yaml
```

**Comment by crivera8602** [comment]
i am also experiencing the same.

**Comment by bschatzow** [comment]
I was told on discord that this is working as designed (wad). I said this makes no sense but was over ruled.  Glad you opened an issue.

**Comment by Skeletorjus** [comment]
> I was told on discord that this is working as designed (wad). I said this makes no sense but was over ruled. Glad you opened an issue.

If you have the same issue that I am, then it is absolutely not working as designed.
It was designed, and for a while worked like, what is shown here:
https://www.home-assistant.io/blog/2020/02/05/release-105/#improved-zones-editor

I have no circles to drag anymore.

**Comment by zsarnett** [comment]
This should be fixed in the 2022.5 release

**Comment by Skeletorjus** [comment]
> This should be fixed in the 2022.5 release

Thanks a bunch! I just tried 2022.5.b0, but it's still not working there. Do you know if the fix will be included during the beta period?

**Comment by Pe-MaKer** [comment]
I have exactly the same issue. I can't even tell since which release the editing of the zones no longer works.
Are there any details about the fix in 2022.5 @zsarnett ? Has the fix been merged for today's release?

**Comment by Pe-MaKer** [comment]
![image](https://user-images.githubusercontent.com/44093812/166883446-8b90c21b-b814-4ed9-b93e-94b0d04cf8eb.png)
Sadly, the map editor is still not working in 2022.5.0 
I still can't set the pin nor see or change the radius.

**Comment by aptonline** [comment]
Same here with Home Assistant Core 2022.5.5

**Comment by aptonline** [comment]
Is this, core functionality, being fixed in the upcoming 2022.6.0 release?

**Comment by zsarnett** [comment]
I can't replicate this issue...

Firefox:
![CleanShot 2022-06-24 at 17 41 36](https://user-images.githubusercontent.com/18730868/175719682-091d179b-e478-42d7-84d1-85486ec62876.png)

Safari:
![CleanShot 2022-06-24 at 17 41 55](https://user-images.githubusercontent.com/18730868/175719703-e63aeae8-955a-45e6-803d-775ec44917a5.png)

Chrome:
![CleanShot 2022-06-24 at 17 42 10](https://user-images.githubusercontent.com/18730868/175719728-77d25fab-a2fd-49a0-9466-45d2b86c7a57.png)

**Comment by crivera8602** [comment]
It's working now on my chrome browser.![image](https://user-images.githubusercontent.com/63074950/175722038-863c0978-6e67-49f9-934b-dde9f9426ccb.jpeg)

**Comment by Skeletorjus** [comment]
@zsarnett This is so strange, I have it on all devices and browsers. Could the editor be choking on some configuration? Is there anything I can do or send to you to help debug this issue?
I recently moved from supervised to docker, and the issue came along with my config-folder to the new install, so there has to be something in my config/setup that is causing this.

@crivera8602 The screenshot you posted is not the zone editor.

**Comment by crivera8602** [comment]
@Skeletorjus my zone is configured in the configuration.yaml. It was as giving me the same error where the map wasn't showing properly. If i generate a new zone, you have a new configurable zone in the front end.🤓 ![image](https://user-images.githubusercontent.com/63074950/175766338-5f54df7a-43f4-4427-a68b-4402434526a9.jpeg)

**Comment by Skeletorjus** [comment]
@crivera8602 Vet interesting! I have no zones configured in yaml. Tried defining my home-zone in yaml, but it didn't make any difference.
Do you know what changed in your setup when you resolved the issue?

**Comment by crivera8602** [comment]
@Skeletorjus Yeah i figured it wouldn't make a difference since at the end it's the frontend that's giving the issues. I just use the yaml way to make the zone smaller than the UI allows. What's device are you running your home assistance on? I'm on a ssd Rpi4OS 64bit. Wondering if it's your setup that's causing the issue. Might help developers to narrow down the issue.

**Comment by Skeletorjus** [comment]
Debian 10, docker (supervised before that). Thing is, i had this working some time ago, but somewhere along the way, and I don't know when or why, it broke.
Maybe something goes wrong while the editor is parsing the zones? The strange thing is that zones are working perfectly on the map and as entities, it is only the editor itself that is having troubles.

**Comment by crivera8602** [comment]
@Skeletorjus hmmm that's strange wish i can be of more help. I'm sure the developers will figure it out. Home assistant is evolving each day. So i know they have laundry list of things to accomplish.

**Comment by Skeletorjus** [comment]
I just realised that I get an error in Chrome devtools when I open the zone editor:
![image](https://user-images.githubusercontent.com/9031934/176179379-5beb7a7d-238c-4d69-8565-b6598b532eb7.png)

Full output:
```
ha-locations-editor.ts:49 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'enable')
    at ha-locations-editor.ts:49:1
    at Array.forEach (<anonymous>)
    at s.value (ha-locations-editor.ts:49:1)
    at 008758dd.js:1:8518
(anonymous) @ ha-locations-editor.ts:49
value @ ha-locations-editor.ts:49
(anonymous) @ 008758dd.js:1
Promise.then (async)
(anonymous) @ 008758dd.js:1
Promise.then (async)
s @ 008758dd.js:1
E @ typography.js:181
t @ typography.js:181
p @ styles.ts:369
T @ styles.ts:369
_$AI @ styles.ts:369
S @ styles.ts:369
update @ styles.ts:369
performUpdate @ styles.ts:369
scheduleUpdate @ styles.ts:369
_$EC @ styles.ts:369
await in _$EC (async)
requestUpdate @ styles.ts:369
o @ styles.ts:369
b @ styles.ts:369
w @ styles.ts:369
F @ ha-selector-icon.ts:9
E @ typography.js:181
t @ typography.js:181
render @ 5ff249ff.js:1
update @ 5ff249ff.js:1
_$AS @ styles.ts:369
D @ styles.ts:369
_$AI @ styles.ts:369
m @ styles.ts:369
T @ styles.ts:369
_$AI @ styles.ts:369
S @ styles.ts:369
update @ styles.ts:369
performUpdate @ styles.ts:369
scheduleUpdate @ styles.ts:369
_$EC @ styles.ts:369
await in _$EC (async)
requestUpdate @ styles.ts:369
o @ styles.ts:369
b @ styles.ts:369
w @ styles.ts:369
F @ ha-selector-time.ts:8
E @ typography.js:181
t @ typography.js:181
p @ styles.ts:369
T @ styles.ts:369
_$AI @ styles.ts:369
m @ styles.ts:369
T @ styles.ts:369
_$AI @ styles.ts:369
A @ styles.ts:369
_$AI @ styles.ts:369
m @ styles.ts:369
T @ styles.ts:369
_$AI @ styles.ts:369
S @ styles.ts:369
update @ styles.ts:369
performUpdate @ styles.ts:369
scheduleUpdate @ styles.ts:369
_$EC @ styles.ts:369
await in _$EC (async)
requestUpdate @ styles.ts:369
o @ styles.ts:369
b @ styles.ts:369
w @ styles.ts:369
a @ ha-form-string.ts:24
E @ typography.js:181
t @ typography.js:181
p @ styles.ts:369
T @ styles.ts:369
_$AI @ styles.ts:369
S @ styles.ts:369
update @ styles.ts:369
performUpdate @ styles.ts:369
scheduleUpdate @ styles.ts:369
_$EC @ styles.ts:369
await in _$EC (async)
requestUpdate @ styles.ts:369
set @ styles.ts:369
value @ ha-textfield.ts:7
c @ ha-svg-icon.ts:5
await in c (async)
(anonymous) @ ha-svg-icon.ts:5
i @ typography.js:181
value @ ha-config-zone.ts:52
value @ ha-config-zone.ts:52
handleEvent @ styles.ts:369

```

**Comment by Skeletorjus** [comment]
> What browser are you using?

Chrome 103.0.5060.53 (64-bit), but I experience the issue described in the first post on all browsers I've tried both on desktop and Android.

**Comment by Skeletorjus** [comment]
Alright, I think I figured this out!

It seems like there are some frontend resources that are messing up the map. I went through all mine and removed the ones that were labeled as `JavaScript File (deprecated)`
The one that I _think_ ended up being the culprit was the vertical-stack-in-card. After removing that resource I had a fully functioning zone editor again!
The card could be reinstalled through HACS and was then properly registered as a JavaScript module.

@aptonline, @Pe-MaKer and @bschatzow, could you take a trip through your resources and see if this fixes it? In the upper right corner, click the three dots and select "Edit dashboard", click the three dots again and select "Manage resources" and remove the deprecated JavaScript files.

**Comment by zsarnett** [comment]
Thanks for investigating!
