### ISSUE TITLE
history-graph card doesn't auto update with new values since 2022.06.0

### ISSUE THREAD

**Issue by sargue** [home-assistant/frontend#12859]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Having a dashboard with a history-graph card usually updated automatically with any new value. Now it doesn't until you refresh the page.

My specific example is a custom energy graph that shows the last 3 hours of energy production / consumption. I usually have it opened on a secondary monitor to keep an eye on it. Now I need to reload the page to see the updated graph.

It's always been with `refresh_interval` not set (so default 0). I assume that meant update on new values. Anyway I tried setting a interval value (e.g. 60 seconds) but the issue remains (no updates at all).

### Describe the behavior you expected

The graph should update with new values.

### Steps to reproduce the issue

1. Create a history-card with some sensor that changes frequently enough (e.g. 1 minute)
2. Wait until there's enough new data
3. It doesn't show the updated graph
...

### What version of Home Assistant Core has the issue?

2022.6.1

### What was the last working version of Home Assistant Core?

2022.5.x

### In which browser are you experiencing the issue with?

Firefox 101.10 / Brave 1.39.111 (Chromium 102.0.5005.61) 

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
entity: sensor.solar_production
state: 146
attrs:
 state_class: measurement
 unit_of_measurement: W
 device_class: power
 icon: mdi:solar-power
 friendly_name: solar_production
```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sensor.solar_production
hours_to_show: 1
```

### Javascript errors shown in your browser console/inspector

```txt
No errors shown.
```

**Comment by ildar170975** [comment]
I confirm this with 2022.6.1

**Comment by nixmaster2000** [comment]
Can confirm I'm also having this issue in 2022.6.0 and 2022.6.1

**Comment by bdraco** [comment]
I'm pretty sure the fix for history caching in #12788 is why this no longer works.

Since we aren't recreating the history object every now the timeline element isn't seeing the data change

**Comment by bdraco** [comment]
Reverting #12788 fixes this issue.

Unfortunately that also means the cache is broken again if we do that.

**Comment by ildar170975** [comment]
Is a fix for this problem - part of 2022.6.4 ?
Unfortunately, the problem still exists in 2022.6.4.

**Comment by sargue** [comment]
I don't think so. I don't know how the deployment process works but there's no new release for this project (frontend) after this merge. I don't think it will take long, releases seem to happen quite frequently.

**Comment by bdraco** [comment]
Frontend needs to be updated before this fix released. That was not done in .4.

**Comment by ildar170975** [comment]
Looking forward to it! Thank you, guys, very much for all your efforts!

**Comment by Brun059** [comment]
Thank you guys. looking forward to 2022.6.6, hope it fixes the issue.

**Comment by Brun059** [comment]
@bdraco Does anyone have a guess when this fix will be included in a release. Issue still persists in 2022.6.6

**Comment by bdraco** [comment]
2022.7

**Comment by Brun059** [comment]
Danke / Thanks, so another 2..3 weeks to wait

**Comment by aronbardsley** [comment]
I spent a couple of hours debugging this issue in chrome myself I found that the data property on the stateHistory object was being manipulated during an incremental update from web socket. 

Since the data object was only manipulated (and not created anew), the comparison for state changes on element inputs is done using a shallow comparison (i.e. ==), the data property was never detected as "changed" by the line graph component as it was in fact the same object and therefore it never passed that property to the willUpdate function of the line graph class and so never re-generating the data into the line graph class.

The fix of the original code seems simple enough to me, rather than appending to the existing data object, a new object should be created and its properties set (i.e. a deep clone would be preferrable). 

But I suppose a revert will also solve the issue.

**Comment by aronbardsley** [comment]
@bdraco Information is below. It's not enough to just create new timeline and line properties on the state history, you need to go deeper. 

See my screenshots below, I hope this explains it. 
![image](https://user-images.githubusercontent.com/16513722/174503785-bd032408-4dde-4704-870a-d2b459773c09.png)
![image](https://user-images.githubusercontent.com/16513722/174503787-0ff508d6-721d-4f1a-8c19-dd277f9a9665.png)
![image](https://user-images.githubusercontent.com/16513722/174503791-1fa4f9e0-6a41-4e4d-b81a-7f4d891564a3.png)

**Comment by Brun059** [comment]
> 2022.7

unfortunately not,  :-(   . Just installed 2022.7.0. history graph is still not refreshing.

**Comment by ildar170975** [comment]
In my setup - graphs are refreshing after a state's change.

**Comment by Brun059** [comment]
@ildar170975 , thanks for bringing it up.
History bars (without UoM) have not been refreshing for a long time, don't know since when. 
History [line-] graphs seam to refresh again at "some" interval, I look into what "some" is later but it is not as frequent as with 2022.5 and likely not the refresh_interval.
