### ISSUE TITLE
Schedule helper selection desapearing

### ISSUE THREAD

**Issue by g-nogueira** [home-assistant/frontend#13685]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try adding a Schedule helper and selecting a time, the time disappears as soon as I click elsewhere.
![Animation](https://user-images.githubusercontent.com/27465604/189507707-1e366cc2-2c48-4107-9445-eb858fc6ddf8.gif)

### Describe the behavior you expected

To be able to select my schedule and save it correctly.

### Steps to reproduce the issue

1. Navigate to the Helpers page (i..e, /config/helpers)
2. Click on "Create Helper" and select "Schedule"
3. Give it a name (e.g., "Test")
4. Select a timeframe (e.g., Mon 9p to 11p)
5. Select another timeframe (e.g., Tue 5p to 6p)

### What version of Home Assistant Core has the issue?

2022.9.1

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.102

### Which operating system are you using to run this browser?

Windows 11 Insider Preview 25197.1000

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

Don't know if it is expected, but seems weird. I noticed that, at the moment I select a timeframe, it keeps removing and adding the same HTML div element.
![Animation1](https://user-images.githubusercontent.com/27465604/189508175-3c42fc9d-2e1b-4944-b28e-ce1813fd08c6.gif)

**Comment by g-nogueira** [comment]
Seems to be the same as #13547

**Comment by boardyuk** [comment]
I can confirm I have this same issue.

Strangely things seemed to be working fine yesterday as I was creating schedules and replacing other helpers, however, this morning I went to edit a schedule and it was completely blank, any new ones I created resulted in the same behaviour as above.

I've tested this on multiple browsers and also on multiple devices. Everything is completely up to date on my installation also.

**Comment by jul-fls** [comment]
Same problem here, i tried to remove any cache data on google chrome, change browser, change device (laptop vs desktop vs phone) and reboot them all (including home assistant server) and still the same with old schedules (tried to remove and recreate) and new schedules it does the same.

**Comment by Orvadet** [comment]
Same here, regardless of cache, browser and it's even the same on a new fresh install of HA.

**Comment by tdejneka** [comment]
I see the same problem (2022.9.1 with Microsoft Edge/Android). 

In addition, if I view an existing `schedule` entity after it has been created/edited, none of the scheduled time periods are displayed. I know the time periods exist because the entity's `next_event` attribute contains a datetime.

**Comment by husjon** [comment]
Just found myself in the same position.
I created a schedule for my vacuum as soon as I upgraded to 2022.9 and it worked like a charm as in I could see the scheduled times, but now I cannot see or update the scheduled times.

I've looked at `homeassistant/config/.storage/schedule` and the schedules are set as they should.
https://pastebin.com/wME9G43G

**Comment by husjon** [comment]
So, I just tried to change my computers time and after reloading and opening the settings for the schedule helper the specified times were visible again.
What I'm seeing is that on Sundays, the scheduler does not show the timeslots.

Could it be that there is a time of day indexing issue with homeassistant / scheduler?

## 2022-09-10 (Saturday)
![image](https://user-images.githubusercontent.com/554229/189538070-9a42e441-47ba-49fa-9d39-75f69c876b82.png)


## 2022-09-11 (Sunday)
![image](https://user-images.githubusercontent.com/554229/189538099-c59fc1d0-87d5-4ef3-b0a2-8d1fb2186f54.png)


## 2022-09-12 (Monday)
![image](https://user-images.githubusercontent.com/554229/189537954-164aeb9e-57a9-4a67-9aa4-cb05fc238923.png)

**Comment by esev** [comment]
I agree with @husjon here. All the schedule entries were missing on the schedule yesterday. They appeared again today (Monday). Nothing changed, as far as I am aware of, besides the date/time on my computer.

**Comment by g-nogueira** [comment]
Well, it turns out I'm also able to use the Schedule Helper today. It seems it doesn't work on weekends?...

**Comment by zigomatichub** [comment]
Updated to HA 2022.9.3 - the file schedule in .storage is saved correctly but the display is not reflecting that file even in inprivate mode. I don't understand what's happening and how it works even after looking into developer mode

**Comment by fchiari** [comment]
Hello,
If I select several days and hours it works and the selection remain.
Nevertheless it is not possible to select half an hour. It will be updated and always like this:
1. 9:00-9:30 will be transformed in 9:00-10:00
2. 12:30-13:00 will be transformed in 12:00-13:00

My software versions are:
Home Assistant 2022.9.4
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.2 - latest
Thanks for the help

**Comment by StormyKnight17** [comment]
I could not get Sunday periods to stay shown. I would get the overlapping periods error message.

**I changed the "first day of week" setting in the User profile to Monday & then I was able to fully create a schedule helper.**

Once created you could switch it back to Sunday if you wanted.

[https://rc.home-assistant.io/blog/2022/11/02/release-202211/#the-first-day-of-the-week](https://rc.home-assistant.io/blog/2022/11/02/release-202211/#the-first-day-of-the-week)

Mine had defaulted to Sunday, but even manually setting it to Sunday it did not work.

Home Assistant 2022.11.1

**Comment by husjon** [comment]
I just played around with the `First day of the week` settings

Letting my computer time use NTP (currently `Mon 2022-11-07 13:49:44 CET`)

Setting the `First day of the week` to Monday, which is my locale default, all seems fine.
![image](https://user-images.githubusercontent.com/554229/200315529-51815f8a-90c2-4506-9e43-ebb90e2d8cde.png)


Setting the `First day of the week` to Sunday, the schedule is missing on Sundays.
![image](https://user-images.githubusercontent.com/554229/200315191-783908a7-63a1-4a30-943e-dd9e847bd0e8.png)


Setting the `First day of the week` to Saturday, the schedules are missing on both Saturdays and Sundays.
![image](https://user-images.githubusercontent.com/554229/200315303-faae1d42-56aa-48bc-8023-4f74f5d19d2e.png)


My hunch is still indexing related :thinking: 
https://github.com/home-assistant/frontend/issues/13685#issuecomment-1242997138

**Comment by ScottG489** [comment]
I haven't been able to follow all of the issues others have had, but I thought I'd report mine.

I also had issues trying to create a schedule on Sunday. It seemed like time's set on Sunday itself would stay selected in the UI, but when I tried selecting other days they would replace each other.

Now it's Monday and I'm seeing different weird behavior. Selecting times for different days are no longer causing other days to disappear, but I just tried saving and reopening a schedule and all the days except Sunday are now displaying in the UI.

To further clarify, it seems like the right dates are actually being saved and selected, this is just a UI problem. I draw this conclusion because I'm also seeing the "Overlapping times" error when I try to make a selection on a day after it's disappeared.

**Comment by martienpoels-bank2loyalty** [comment]
I have the same problem. Schedule times are visually removed as soon as another day is clicked.

**Comment by honzas78** [comment]
Same issue.

HA version 2022.11.2

Today on Friday I can place all schedules Mo to Sat, but not on Sunday. If I try to place more than one schedule on Sunday, previous one disappeared. 

My system default setting is first day is Monday, but in the schedule editor is first Sunday.

When I try to save settings, I get "overlapping error".

![image](https://user-images.githubusercontent.com/103874977/201422973-7d8fb3e3-2315-4d57-bc9a-17a637749708.png)

**Comment by andrewbpowers** [comment]
The problem still exists!

**Comment by spacegaier** [comment]
I would assume I fixed that via https://github.com/home-assistant/frontend/pull/14529

**Comment by husjon** [comment]
@spacegaier The issue is fixed for `Start of Week = Monday` but unfortunately for everything else is still broken :/

* monday: working -> https://youtube.com/shorts/d3j16kE6PeQ
* saturday: not working -> https://youtube.com/shorts/Jlq80j3m9o4
* sunday: not working -> https://youtube.com/shorts/0g53m5wKHgo

**Comment by spacegaier** [comment]
> @spacegaier The issue is fixed for `Start of Week = Monday` but unfortunately for everything else is still broken :/
> 
>     * monday: working -> https://youtube.com/shorts/d3j16kE6PeQ
> 
>     * saturday: not working -> https://youtube.com/shorts/Jlq80j3m9o4
> 
>     * sunday: not working -> https://youtube.com/shorts/0g53m5wKHgo

Saturday was not covered in my previous PR but will be with https://github.com/home-assistant/frontend/pull/14566. But Sunday should work. Are you on the dev version?

**Comment by husjon** [comment]
I was on the lateast release.
However with the latest dev release (f3ea5697f44b / 2023.1.0.dev20221205)
Seems like sundays are still an issue.

Clean dev instance. https://youtu.be/Ua9Wt0DKgEU

**Comment by spacegaier** [comment]
With "dev version" I mean directly here the frontend repository, not the nightly builds, since in the nightly my fixes are not yet in (they were only merged into the codebase today). In our wording dev version != nightly version.
