### ISSUE TITLE
Z-Wave JS `Stop Searching` button does not work

### ISSUE THREAD

**Issue by DEC888** [home-assistant/frontend#14393]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi,

The Z-Wave JS app always comes up with a "searching for device" status (see attached screenshot), which prevents me from adding and removing devices, I tried clicking the STOP searching button, but it doesn't work, any suggestions?
![Issue of Z-Wave JS](https://user-images.githubusercontent.com/56387118/202160656-b9ef754d-f827-4b57-b10d-1e1b2e61cd0a.jpg)

### Describe the behavior you expected

Click the STOP searching button, then the searching should be stopped.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

 20221108.0 - latest

**Comment by MrMxyzptlk** [comment]
Yep, same for me.
Latest version of addon and All of Home Assistant.

**Comment by 6254sagebrush** [comment]
any fixes ?

**Comment by dcnoren** [comment]
Same issue for me

**Comment by ushroff** [comment]
I have the same issue

**Comment by rcflores84** [comment]
I have the same issue

**Comment by ekouters** [comment]
I had the same issue. Restarting HASS had no effect. 

What solved it for me was disabling and re-enabling the Zwave JS integration.

I was trying to pair a device, and the device was not detected. After disabling and re-enabling the Zwave JS integration the device was immediately detected and paired successfully.

**Comment by LinuxfarmerHH** [comment]
Treiber-Version: 10.22.3
Server-Version: 1.28.0

Device Aetoec Gen-5 stick. Problem triggered while try'in to exclude a device, from than it was in neverending search. No change by try'in to include or exclude a device. No change through several hassio reboots.

Working bugfix is: Disable Z-Wave JS, re-enable and reboot home assistant.

So bug exist still on and should be fixed.

**Comment by mfsiii** [comment]
I have a Zooz 800 and I'm seeing it too. It's like the controller get stuck in that mode I just have to wait a while until it is out. The button doesn't work.

**Comment by galoi9** [comment]
My systems with Aeotec 5 does the same, the system is bogged down always searching. I can stop it, but then it starts on its own again.

**Comment by scripter13** [comment]
I was dealing with this issue after a terrible pairing experience between 2 Aeotec devices. Stopping the Z-Wave JS UI and restarting it in the "Add-Ons" Settings menu finally presented an actual error message, but HA was successful in retrying the connection. 

If this doesn't resolve, it might be time to make a backup of your zwave network, factory reset the hub, and attempt to restore your backup.

**Comment by CodeCat5** [comment]
I just ran into this issue as well. I was trying to exclude a device before adding it, but it never found anything and kept searching for over a day. I tried disabling Z-wave JS, restarting my HA container, and re-enabling Z-wave JS but that didn't work. I had to disable Z-wave JS and then reboot the host machine that HA is running on before it finally stopped searching.

**Comment by karwosts** [comment]
I would maybe recommend maybe someone open up a core issue for zwave_js for this, as I suspect it's probably not a frontend issue. All frontend does on clicking that button is call a core zwave_js API command, either stop_inclusion or stop_exclusion. If it doesn't stop that's a core responsibility.
