### ISSUE TITLE
Dashboard background gets scaled up

### ISSUE THREAD

**Issue by Lux315** [home-assistant/frontend#16406]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since 2023.5 the background image on every view gets scaled up by the length of the view. The  longer the view, so is the image more zoomed in.

This actually just happens on ios so far. But in the app and safari. Samsung app is fine

### Describe the behavior you expected

normal scales background

### Steps to reproduce the issue

1. set background image
2. use an ios device
3.
...

### What version of Home Assistant Core has the issue?

2023.5

### What was the last working version of Home Assistant Core?

2023.4.x

### In which browser are you experiencing the issue with?

Safari and mobile app

### Which operating system are you using to run this browser?

IOS

**Comment by Lux315** [comment]
If i remove the "fixed" in the raw config editor, the same happens on the samsung app. Place back fixed und samsungs view is just fine. IOS keeps beeing wrong.

Seems like theres a problem with the "fixed" for ios

**Comment by piitaya** [comment]
Can you provide some screenshot with current behavior and expected behavior. Also, can you provide the options you set in the raw config editor?

**Comment by Lux315** [comment]
Code:

background: center / cover no-repeat url('/local/background.jpeg') fixedheader_cards:

How it should look like: (Now on Android:
![image](https://github.com/home-assistant/frontend/assets/67388320/fb968a48-5581-4691-bacb-13c7b1ac9913)
![image](https://github.com/home-assistant/frontend/assets/67388320/20234c08-5c6b-404c-9358-dd77ceef35e3)
![image](https://github.com/home-assistant/frontend/assets/67388320/193f6fae-9a6c-49a2-8267-1bdfe5409b64)
![image](https://github.com/home-assistant/frontend/assets/67388320/ac5c07f6-8226-40b1-a909-4a808321bce5)

And this is how it looks on all ios devices:
![image](https://github.com/home-assistant/frontend/assets/67388320/0ce22d3e-d498-4444-87cd-157d7f27779d)
![image](https://github.com/home-assistant/frontend/assets/67388320/4e1b60cc-dc1c-4d81-93db-db834318097d)
![image](https://github.com/home-assistant/frontend/assets/67388320/a896a440-6102-478b-998c-e6da411f764d)
![image](https://github.com/home-assistant/frontend/assets/67388320/88d531a8-647c-4262-9756-8c1eb341f6ac)

On Android the background is fixed but on ios its getting zoomed in.

**Comment by Lux315** [comment]
It should look like this:
https://github.com/home-assistant/frontend/assets/67388320/8cf0a971-5e25-4c7c-9336-ef1175b7c781

But it looks like this on ios:
https://github.com/home-assistant/frontend/assets/67388320/53d62587-cf0b-4c5f-a214-95e8a28bde41

**Comment by piitaya** [comment]
Seems like a iOS issue. `background-attachment: fixed` is not supported on iOS.
https://developer.apple.com/forums/thread/99883
https://caniuse.com/background-attachment

**Comment by Lux315** [comment]
@piitaya Thanks for your answer before.

Ive just seen that the apple
home app does have a fixed background aswell, so this should really work and seems to be an issue with 2023.5.

Id be very happy if we could get back the fixed background. 

Thx for your work here!

**Comment by Lux315** [comment]
@piitaya 

Thats still a problem. Do you mind taking a look?

**Comment by Lux315** [comment]
I had another instance running on 2023.4.4 on a VM, background works fine

updated to 2023.6, background is broken again.

So im sure the update broke this function.

**Comment by andre4715** [comment]
Hello,

i have exactly the same Problem but can't find a solution until today. Did you find a solution net ?

**Comment by Lux315** [comment]
@andre4715 

no, i couldnt find any solution for that. Hoping that @piitaya answers someday.

**Comment by piitaya** [comment]
I already responded that it's a Safari issues : https://github.com/home-assistant/frontend/issues/16406#issuecomment-1540486019 
Also, I'm unable to have it working in a older version (I tested with February release). Even on Chrome, fixed background doesn't work on this version.

**Comment by andre4715** [comment]
I can confirm this. Only in 2023.4 ist was working on Safari or ios, but i also had scrolling issues in Dashboard. Sinne 2023.5 background Is scaled in Safari but scrolling Is Smooth. Now i still use 2023.4. 

@piitaya ….do you think we will get a Solution in near future? Don‘t want to stay in 2023.4 for ever.

**Comment by piitaya** [comment]
I don't have a solution because adding nested scrolling will introduce scrolling issue.

**Comment by Lux315** [comment]
Thanks for your answers @piitaya 

The fixed background worked for me since 2022.11 until 2023.4

i asked @Petro31 @ Discord and he responded that this ios background works fine (i think that was with 2023.6)

Still thanks for trying to fix this!

**Comment by andre4715** [comment]
I have to correct ne. At the moment i am using 2023.4.6 and the background on Safari/iOS Is fine, and also no issues with scrolling in the Dashboard. Problem with scrolling was before 2023.4.6

@piitaya may something else Is different in 2023.4.6 ? This Version works Perfect for me.

**Comment by Lux315** [comment]
@andre4715 What code are you using to set the background?

Do you set in in the raw config editor or in a theme?

**Comment by andre4715** [comment]
i use the following code in my .yaml

title: 'home'
path: home
icon: mdi:home
background: >-
  center / cover no-repeat url("/hacsfiles/themes/wallpaper/iphone/ha-iphone-home01.jpg") fixed

**Comment by ncodee** [comment]
@piitaya Could you implement some sort of work around for this please?

**Comment by piitaya** [comment]
If you found a workaround, don't hesitate to open a PR. For now, I don't have any workaround to make it works 😕

**Comment by hsph** [comment]
I'm also fighting with this and couldn't find a solution yet.

**Comment by Lux315** [comment]
Couldnt find a solution for now.

Found out that even mp4 videos with this "https://github.com/rbogdanov/lovelace-animated-background" even get stretched

**Comment by Lux315** [comment]
This will get a big issue now with the option to set backgrounds from the UI

**Comment by andre4715** [comment]
Because it did. Not work , i now use bubble Card Pop ups. Inside bubble Card Pop up the background Is fixed and Not scaled.Von meinem iPhone gesendetAm 12.06.2024 um 11:30 schrieb Sebastian H. ***@***.***>:﻿
I'm also fighting with this and couldn't find a solution yet.

**Comment by hsph** [comment]
I found a solution today. The only minor downside is that it displays the background on every page in Home Assistant, not just the dashboard. However, I think it looks quite nice. With a bit more tinkering, you can probably figure out how to prevent this.

Anyway, here's how I fixed it for me:
After a lot of trying around, researching and frustration, I finally found a way to fix iOS' webkit behavior :slight_smile: I only did some quick testing so far, so please let me know if there is anything wrong or weird.

**Step 1: Create a css file: /hacsfiles/dashboard_resources/background-fix.css**

```
@media (prefers-color-scheme: dark) {
  html::before {
      content: ' ';
      display: block;
      background-image: url('[/path/to/your/light-background') !important;
      background-position: center;
      background-size: cover;
      height: 100vh; width: 100vw;
      top: 0; bottom: 0; left: 0; right: 0;
      position: fixed;
      z-index: -10;
  }
}

@media (prefers-color-scheme: light) {
  html::before {
      content: ' ';
      display: block;
      background-image: url('[/path/to/your/light-background') !important;
      background-position: center;
      background-size: cover;
      height: 100vh; width: 100vw;
      top: 0; bottom: 0; left: 0; right: 0;
      position: fixed;
      z-index: -10;
  }
}
```

You can also remove the @media at-rule if you don't want to have separate backgrounds for light and dark. 

**Step 2: Add this file as a dashboard resource**
In Home Assistant go to Settings > Dashboards > ... (top right corner) > Resources.

Add a new resource (bottom right corner).
URL: /hacsfiles/dashboard_resources/background-fix.css
Resource type: Stylesheet

**Step 3: Clear cache and reload**
As the title says, clear your caches and reload the page. The fix should be applied now. 

**Step 4: (Optional) disable theme background**
If you have a theme which sets a background image, you have to disable that.

**Comment by piitaya** [comment]
I installed iOS 18 to test if it will be resolved and of course, it's not resolved... 😡 I also checked a similar solution as @hsph  few weeks ago but It will disable to ability to set a no-fixed background for those who wants.

We introduced UI to set a background in the last release and we will iterate to improve the background customization. This issue will be taken into account 👍

**Comment by Lux315** [comment]
@piitaya Thank you very much! Happy to hear this

If any testing is needed, im happy to help!

**Comment by GGSSDD** [comment]
Hi,
Any development on the subject?

**Comment by piitaya** [comment]
It should be fixed in next release (`2024.11`).

**Comment by Lux315** [comment]
That sounds great! Thank you

What caused the issue?

**Comment by piitaya** [comment]
`background-attachment: fixed` was never supported by iOS, we now use a workaround to fixed it.

**Comment by Lux315** [comment]
@piitaya The issue is still there for me. Tried setting up the background in a theme, directly in raw config mode and in the UI but the image still isnt fixed

**Comment by GGSSDD** [comment]
Same here... I reseted the frontend cache as well, but to no avail!

**Comment by piitaya** [comment]
Fixed background using the UI is not supported yet but we are working on it. It's currently only supported using theme with the `lovelace-background` variables. What value did you set for the theme variable?

**Comment by Lux315** [comment]
Im using this in my themes:

`lovelace-background: center / cover no-repeat url("/local/muted.webp") fixed`

**Comment by piitaya** [comment]
Thank you!
My bad, there was a typo when I refactored the code, we will push a fix in the next patch release (certainly on Friday)

**Comment by GGSSDD** [comment]
I can confirm partial functionality. I have a dashboard comprised of multiple tabs, 2 of them are regular views and the most of them are set to subview type. It's behaving properly in the subview tabs but not in the regular ones, it's still getting stretched there.

**Comment by piitaya** [comment]
> I can confirm partial functionality. I have a dashboard comprised of multiple tabs, 2 of them are regular views and the most of them are set to subview type. It's behaving properly in the subview tabs but not in the regular ones, it's still getting stretched there.

With the same background theme property? There is no difference between views and subviews so it's weird. Check that you have the same theme and the same background for all the views.

**Comment by GGSSDD** [comment]
I'm using the iOS Themes custom repository. I have the same theme set up for the entire dashboard (Overview (default)) via the user settings, hence the same background-image property everywhere: `"center / cover no-repeat fixed url('/local/ios-themes/homekit-bg-light-green.jpg')"`. I've also reseted the frontend cache to no success.

The main tab and "3D PRINTER: CR-10S" are regular view tabs, while the "Lights" tab is a subview type:
https://github.com/user-attachments/assets/76f0deb9-f6c0-4b5d-a3fd-92de2975d564

Settings as per User:
![user_config](https://github.com/user-attachments/assets/07e9ee98-ce7c-4453-b5d3-2fb9e3bcbd62)

Theme config:
![theme_config](https://github.com/user-attachments/assets/1f7806de-1ef3-4d8a-ab3d-d23931f7bf51)

**Comment by piitaya** [comment]
Oh I see! Can you set the value directly to lovelace-background instead of using var(--background-image)? I'm not sure the workaround works with additional variable in between.

**Comment by GGSSDD** [comment]
Sorry, it didn't fix it...

**Comment by piitaya** [comment]
Can you share the yaml of your dashboard?

**Comment by GGSSDD** [comment]
I would gladly do it if i knew what the best way to do it would be... the dashboard goes roughly to 46000 yaml lines... any suggestions?

**Comment by piitaya** [comment]
You can check if you have no background setting in the view that can override the background from your theme.

**Comment by GGSSDD** [comment]
Thanks to you now I know what was wrong with it... I had the following line in the yaml of both views: `background: {}`. Removing the line solved the issue. I honestly don't know how it got there, and why only in the regular views and not in the subviews as well.

Thank you very much, I really appreciate it, I appreciate your work and patience and sorry for troubling you for nothing.

**Comment by piitaya** [comment]
I'm glad it's solved now 🙂

**Comment by Lux315** [comment]
I had the exact same issue😅

Looks so much more smooth now, thanks @piitaya !
