### ISSUE TITLE
Unable to edit schedule (created using Helper) 

### ISSUE THREAD

**Issue by Mossi777** [home-assistant/frontend#19525]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Schedule editor is not available from the Dashboard. 

### Describe the behavior you expected

The editor should be displayed to allow the schedule to be edited.

### Steps to reproduce the issue

A schedule entity has been added to the dashboard.  When it is clicked, it opens the History and Logbook popup as expected;

![image](https://github.com/home-assistant/frontend/assets/3333564/359487e2-0edd-43e0-a0c1-ea02134b24c8)

If the Settings button is clicked, the schedule editor is not displayed;

![image](https://github.com/home-assistant/frontend/assets/3333564/6d2c6f4d-6a2a-476a-b68b-39b6e28e2edd)

### What version of Home Assistant Core has the issue?

2024.1.5

### What was the last working version of Home Assistant Core?

I first noticed it in 2024.1.3

### In which browser are you experiencing the issue with?

Google Chrome, Brave Browser, Safari and Microsoft Edge

### Which operating system are you using to run this browser?

Windows 11 Home, Apple Sonoma 14.2.1

### State of relevant entities

```txt
The schedule entity shows the expected state (on/off) based on the original schedule set up using the Helper.
```

**Comment by karwosts** [comment]
I see this bug sometimes, but then usually after a hard refresh of the page it works after that. Have you tried that?

**Comment by Mossi777** [comment]
Interesting!

On initial opening of the web page, this issue is present.  Pressing the 'Reload this page' button resulted, as you said, the schedule editor opening as expected.

This schedule is on a separate view on the dashboard (Hot Water).  There are in fact 8 views on the dashboard.

The initial page loaded is the default home page.  If I reload this default (Home) view and then switch to the Hot Water view, this issue is still apparent.  If I select any of the other views and reload the page, then move to the Hot Water view, then the issue is not present.

View tabs urls in case they provide a clue.

![image](https://github.com/home-assistant/frontend/assets/3333564/ecf685dd-499a-49fc-8da9-34a89a8cab2c)
![image](https://github.com/home-assistant/frontend/assets/3333564/6f8eb93e-b4f2-42ab-bb20-eacdd15cdd67)
![image](https://github.com/home-assistant/frontend/assets/3333564/0c6732c9-14e4-4193-b3d9-be750b697dad)
![image](https://github.com/home-assistant/frontend/assets/3333564/0fa3c389-c57e-4308-ae1a-2c967aadfce1)
![image](https://github.com/home-assistant/frontend/assets/3333564/e6991a24-1039-4eb7-b909-92e5f6f51c6c)
![image](https://github.com/home-assistant/frontend/assets/3333564/023e8d7b-df61-4854-9dcc-1e0a770e0361)
![image](https://github.com/home-assistant/frontend/assets/3333564/04e266dc-b49c-424f-aeb0-311fdd76b1a7)
![image](https://github.com/home-assistant/frontend/assets/3333564/36c543b9-8012-4501-bfbb-94a9707d8e02)

**Comment by VNRARA** [comment]
Same problem here. The JS for it just seems to not wanna load. I'm behind NGINX proxy manager and cloudflare. 

Could not load content for https://[redacted].nl/unknown/node_modules/@fullcalendar/timegrid/internal.js (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)

**Comment by VNRARA** [comment]
> I see this bug sometimes, but then usually after a hard refresh of the page it works after that. Have you tried that?

Hard resetting the app is not what I want to be able to use the app. I'll prolly switch to a HACS scheduler instead because the built in is useless in it's current form.

**Comment by lodzen** [comment]
I am also facing the same issue.
On browser i can edit the schedule after full refresh but on Android not able to edit it.

**Comment by andreala** [comment]
Same issue here.
Core
2024.10.2
Frontend
20241002.3

**Comment by mikkiste** [comment]
Same issue here:
Core: 2024.11.2
Frontend: 20241106.2
Few times before it helped to clear browser data, but now it doesn't help at all :-( It would be much appreciated if somebody could fix it, thank you!

**Comment by Gh0stExp10it** [comment]
Same issue here. Doesn't let me edit or create a new Schedule via browser or app.

**Comment by geirskogul** [comment]
I also have this issue and cannot edit a schedule once created on both local and through cloud access

**Comment by andynash** [comment]
Also seeing this problem. A hard refresh in a web browser fixes it, but this doesn't help when using the Android mobile app (have no iPhone to test that). Clearing the app cache doesn't seem to help.

It appears to affect some other helpers too, not just schedule - unfortunately at time of writing I do not recall which ones.

Given we rarely use a web browser to access HA, and need to edit heating schedules etc, this is becoming a bigger problem as we heading into northern hemisphere Winter 😢

It appears to have been a recurrent problem:

https://github.com/home-assistant/core/issues/96197

https://github.com/home-assistant/frontend/issues/21005

Is this being worked on at all by anyone? If not, I guess we will have to shift away from using such helpers as they are unusable as things stand, however I don't want to embark on all that work only to find the problem is then fixed.

**Comment by geirskogul** [comment]
I am still facing this issue as well, to the point that one entire selling point of HA is very nearly unusable to me. 

Holy shit my house would have way more automations if this actually worked.

**Comment by lodzen** [comment]
Issue is still present with HA 2026.2

**Comment by andynash** [comment]
Yep, have just had to get used to this. Workflow is now open HA in browser, visit schedule helper, refresh page, visit again and change schedule, save, return to app.

This isn't a sometimes bug, it is consistent.

Perhaps not many people use schedules? Or maybe there is a known blocking issue (if so would be great to know). Have never had a bug like this one stay unfixed for so long.

But I appreciate we are waiting on someone's personal time and goodwill 😁

**Comment by geirskogul** [comment]
still an issue

**Comment by Mossi777** [comment]
Probably there have been no further comments because we are awaiting fix?  Do we need to comment on issues that are still apparent every week to show it's still active?

**Comment by andynash** [comment]
Correct, unfortunately.

I'm a little confused too - I appreciate this isn't the biggest HA feature, but it seems odd the problem hasn't at least been acknowledged in some way. However I guess there may be many more such issues than I am aware of.

**Comment by geirskogul** [comment]
Scheduling and editing would drastically improve HA for me and its sad this baseline feature is broken

**Comment by andynash** [comment]
Issue is still present in 2026.8.2.

Broken for at least 2 years and 7 months 😢

At least a comment indicating future direction would be welcome - has the schedule domain (and the others affected by this) been abandoned?

**Comment by karwosts** [comment]
I mean personally I would be happy to fix this, it's just that it's so barely reproducible I can't even investigate it. 

On my production server I see this maybe 1/100 times I try to edit something. In development I have never been able to reproduce it (despite trying). 

To the best of my knowledge, this is a minor irritant, not a showstopper or that the entire schedule platform is abandoned. As far as I'm aware, usually just reloading the page makes it work correctly. If there's someone who can literally never make it work, I would be interested to hear more about that, but I haven't seen that comment been made.

**Comment by andynash** [comment]
Thanks, Karwosts, great to hear something regarding this 🙏

Yes, it can be easily fixed in a desktop browser by refreshing, though given the quality elsewhere in Home Assistant, this isn't great.

For those of us who barely touch HA in a browser, let alone on a desktop, it is broken 100% of the time.

Every time I go to edit a schedule, I get a blank screen, remember I have to switch to a browser, find the entity, refresh the page, make the edit and then come back to the app. I forget the other entities this affects, but there are some, but I notice it when busy and don't remember to make a note.

I don't know about iPhone, but as far as I can tell without conducting a survey it appears to be 100% reproducible on Android I'm afraid.

I've managed to swap out schedules for alternatives in many places, but still have some older, more complicated situations where they are still in use, in particular heating.

**Comment by karwosts** [comment]
Hm, yeah I guess that would be more annoying on mobile, fair point.

Anyway not sure what more I can do at the moment, but maybe if someone has a full browser call stack when the error occurs we can add that here, I don't see it posted. Maybe that will give some helpful clue in the future.

**Comment by karwosts** [comment]
And I guess my other question is:

- If we've established that refresh 'fixes' the issue, is there a specific point at which it goes back to 'unfixed'? 

I opened up a schedule in my android and it failed to load. So then I cleared the frontend cache and reloaded the app and it worked that time. And now 10 times I've tried closing the app, moving to other views, reopening the schedule, and it's loading every time. So what do I need to do that will make it stop working again?

**Comment by bferd** [comment]
Since this is where the action is - I suspect a component's Lit styles are getting registered twice during HA's lazy-loading, and the second registration ends up with an empty/null stylesheet. When Lit's fallback `getCompatibleStyle` in `css-tag.js` tries to read `.cssRules` off that null value, it throws. A hard refresh clears the stale registration and lets the native path take over cleanly.

This isn't a schedule specific issue I don't think. Seems to affect all input_*, timer and counter helpers too.

I can reproduce this fairly reliably now. Happens immediately on a fresh navigation straight to my instance's http://IP:port, and also reproduces in a incognito window hitting my external URL. Don't think this is a "session gets stale after a while" thing (no cache, no extensions, no prior navigation in that window).  Hope that helps some.

**Comment by benholl** [comment]
Please do continue to work on this. It is particularly bad on android companion app given there is no way to refresh. A frontend cache clear through debugging does not resolve the issue. I have the issue with every single UI created helper so I am severely impeded in my ability to edit config on mobile which is my primary method - I do not have a desktop computer and rarely use laptop! 

See logs and screenshot attached. 

<img width="1280" height="2856" alt="Image" src="https://github.com/user-attachments/assets/dfc745b1-3f05-407d-86ad-b9bc8194568b" />

```
--------- beginning of system
09-17 07:07:56.212 27808 27808 V ResourcesManager: The following library key has been added: ResourcesKey{ mHash=ebc98043 mResDir=null mSplitDirs=[] mOverlayDirs=[] mLibDirs=[/data/app/~~OodDuzp8rcGCnZcSGPa4Wg==/com.google.android.webview-OHP1Ipw8N5nVH4QNXKVTfQ==/base.apk,/system/framework/android.test.base.jar,/system_ext/framework/androidx.window.extensions.jar] mDisplayId=0 mOverrideConfig=v37 mCompatInfo={480dpi always-compat} mLoaders=[]}
09-17 07:07:56.329 27808 27808 I DisplayManager: Implicitly registering for refresh rate
09-17 07:11:02.082 27808 27808 D InsetsController: hide(ime())
09-17 07:11:02.082 27808 27808 I ImeTracker: io.homeassistant.companion.android:31e0ca57: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
09-17 07:11:12.430 27808 27808 D InsetsController: hide(ime())
09-17 07:11:12.430 27808 27808 I ImeTracker: io.homeassistant.companion.android:21850a61: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
--------- beginning of main
09-17 07:11:12.443 27808 27808 D IntegrationRepositoryImpl: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1789623564709, currentMillis: 1789625472443)
09-17 07:11:12.447 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:12.447 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:12.447 27808 27808 D WebViewActivity: Loading HIDDEN (keepHistory true, openInApp true, serverHandleInsets false)
09-17 07:11:12.447 27808 27808 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): androidx.navigationevent.OnBackInvokedInput$createOnBackAnimationCallback$1@7104b64
09-17 07:11:12.447 27808 27808 D WebViewActivity: Same base URL without meaningful path, skipping load
09-17 07:11:12.447 27808 27808 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): android.app.Activity$$ExternalSyntheticLambda0@2e94f1b
09-17 07:11:12.449 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:12.449 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:12.451 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:12.451 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:12.453 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:12.453 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:13.206 27808 27808 D LocationSensorManager: Received location update.
09-17 07:11:13.217 27808 27808 D LocationSensorManager: Received location update.
09-17 07:11:13.219 27808 27808 D ForegroundServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
09-17 07:11:13.219 27808 28994 D LocationSensorManager: Last Location: 
09-17 07:11:13.219 27808 28994 D LocationSensorManager: Coords:([REDACTED_COORDINATES])
09-17 07:11:13.219 27808 28994 D LocationSensorManager: Accuracy: 36.9
09-17 07:11:13.219 27808 28994 D LocationSensorManager: Bearing: 0.0
09-17 07:11:13.220 27808 28994 D LocationSensorManager: Begin evaluating if location update should be skipped
09-17 07:11:13.220 27808 28994 D LocationSensorManager: Received location that is 311 milliseconds old, 1789625472909 compared to 1789625473220 with source fused
09-17 07:11:13.222 27808 28234 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:13.330 27808 28234 D LocationSensorManager$sendLocationUpdate: Location update sent successfully for 1 as exact
09-17 07:11:13.607 27808 27862 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:13.607 27808 27862 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:13.609 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:13.609 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:13.611 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:13.611 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:13.711 27808 27808 D SensorReceiverBase: Received intent: android.os.action.POWER_SAVE_MODE_CHANGED
09-17 07:11:13.711 27808 27862 D SensorReceiverBase$onReceive: Sensor(s) [power_save] corresponding to received event android.os.action.POWER_SAVE_MODE_CHANGED are disabled, skipping sensors update
09-17 07:11:13.713 27808 27838 D WM-Processor: Processor cancelling c7db025c-820a-4ca0-befb-83b55cd6c31c
09-17 07:11:13.713 27808 27838 D WM-Processor: WorkerWrapper could not be found for c7db025c-820a-4ca0-befb-83b55cd6c31c
09-17 07:11:13.725 27808 27838 D WM-GreedyScheduler: Cancelling work ID c7db025c-820a-4ca0-befb-83b55cd6c31c
09-17 07:11:13.729 27808 27838 W JobInfo : Requested important-while-foreground flag for job14275 is ignored and takes no effect
09-17 07:11:13.729 27808 27838 D WM-SystemJobScheduler: Scheduling work ID 26ee3b94-35ab-413b-8c59-3cc9a086d581Job ID 14275
09-17 07:11:13.731 27808 27808 D WM-SystemJobService: onStartJob for WorkGenerationalId(workSpecId=26ee3b94-35ab-413b-8c59-3cc9a086d581, generation=0)
09-17 07:11:13.733 27808 27838 D WM-GreedyScheduler: Starting work for 26ee3b94-35ab-413b-8c59-3cc9a086d581
09-17 07:11:13.734 27808 27838 D WM-Processor: Processor: processing WorkGenerationalId(workSpecId=26ee3b94-35ab-413b-8c59-3cc9a086d581, generation=0)
09-17 07:11:13.734 27808 27838 D WM-Processor: Work WorkGenerationalId(workSpecId=26ee3b94-35ab-413b-8c59-3cc9a086d581, generation=0) is already enqueued for processing
09-17 07:11:13.735 27808 27808 D WM-WorkerWrapper: Starting work for io.homeassistant.companion.android.websocket.WebsocketManager
09-17 07:11:13.736 27808 27837 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=26ee3b94-35ab-413b-8c59-3cc9a086d581, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
09-17 07:11:13.737 27808 27808 D WM-Processor: Processor 26ee3b94-35ab-413b-8c59-3cc9a086d581 executed; reschedule = false
09-17 07:11:13.737 27808 27808 D WM-SystemJobService: 26ee3b94-35ab-413b-8c59-3cc9a086d581 executed on JobScheduler
09-17 07:11:13.737 27808 27837 D WM-GreedyScheduler: Cancelling work ID 26ee3b94-35ab-413b-8c59-3cc9a086d581
09-17 07:11:13.739 27808 27837 D WM-SystemJobScheduler: Scheduling work ID 26ee3b94-35ab-413b-8c59-3cc9a086d581Job ID 14275
09-17 07:11:13.925 27808 27808 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): androidx.navigationevent.OnBackInvokedInput$createOnBackAnimationCallback$1@7104b64
09-17 07:11:16.845 27808 27808 I ImeTracker: io.homeassistant.companion.android:4f6cf83c: onRequestShow at ORIGIN_CLIENT reason SHOW_SOFT_INPUT fromUser false userId 0 displayId 0
09-17 07:11:16.845 27808 27808 D InsetsController: show(ime())
09-17 07:11:16.845 27808 27808 D InsetsController: Setting requestedVisibleTypes to 511 (was 503)
09-17 07:11:16.848 27808 27808 I AssistStructure: Flattened final assist data: 2408 bytes, containing 1 windows, 6 views
09-17 07:11:16.865 27808 27808 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): android.view.ImeBackAnimationController@8540e5d
09-17 07:11:16.882 27808 27808 D VRI[WebViewActivity]: WindowInsets changed: ime:[0,0,0,1157] 
09-17 07:11:16.901 27808 27808 W InteractionJankMonitor: Initializing without READ_DEVICE_CONFIG permission. enabled=false, interval=1, missedFrameThreshold=3, frameTimeThreshold=64, package=io.homeassistant.companion.android
09-17 07:11:16.987 27808 27808 D Autofill Status: Autofill popup isn't shown because autofill is not available.
09-17 07:11:16.987 27808 27808 D Autofill Status: 
09-17 07:11:16.987 27808 27808 D Autofill Status: Did you set up autofill?
09-17 07:11:16.987 27808 27808 D Autofill Status: 1. Go to Settings > System > Languages&input > Advanced > Autofill Service
09-17 07:11:16.987 27808 27808 D Autofill Status: 2. Pick a service
09-17 07:11:16.987 27808 27808 D Autofill Status: 
09-17 07:11:16.987 27808 27808 D Autofill Status: Did you add an account?
09-17 07:11:16.987 27808 27808 D Autofill Status: 1. Go to Settings > System > Languages&input > Advanced
09-17 07:11:16.987 27808 27808 D Autofill Status: 2. Click on the settings icon next to the Autofill Service
09-17 07:11:16.987 27808 27808 D Autofill Status: 3. Add your account
09-17 07:11:17.183 27808 27808 I ImeTracker: io.homeassistant.companion.android:4f6cf83c: onShown
09-17 07:11:18.621 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:18.621 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:18.625 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:18.625 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:18.626 27808 27862 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:18.626 27808 27862 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:20.194 27808 27808 I ImeTracker: io.homeassistant.companion.android:1865a88a: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false userId 0 displayId 0
09-17 07:11:20.194 27808 27808 D InsetsController: hide(ime())
09-17 07:11:20.194 27808 27808 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): androidx.navigationevent.OnBackInvokedInput$createOnBackAnimationCallback$1@7104b64
09-17 07:11:20.195 27808 27808 D InsetsController: Setting requestedVisibleTypes to 503 (was 511)
09-17 07:11:20.195 27808 27808 D CompatChangeReporter: Compat change id reported: 395521150; UID 10503; state: ENABLED
09-17 07:11:20.201 27808 27808 D VRI[WebViewActivity]: WindowInsets changed: ime:null 
09-17 07:11:20.239 27808 27808 I ImeTracker: system_server:a80d472: onCancelled at PHASE_CLIENT_ON_CONTROLS_CHANGED
09-17 07:11:21.967 27808 27808 E WebViewActivity$onCreate: onReceivedHttpError: 404 : Not Found for: https://[REDACTED_REMOTE_INSTANCE].ui.nabu.casa/unknown/node_modules/@fullcalendar/timegrid/index.js
09-17 07:11:21.968 27808 27808 E WebViewActivity$onCreate: onReceivedHttpError: 404 : Not Found for: https://[REDACTED_REMOTE_INSTANCE].ui.nabu.casa/unknown/node_modules/@fullcalendar/timegrid/internal.js
09-17 07:11:22.928 27808 27808 E WebViewActivity$onCreate: onReceivedHttpError: 404 : Not Found for: https://[REDACTED_REMOTE_INSTANCE].ui.nabu.casa/unknown/node_modules/@fullcalendar/core/internal-common.js
09-17 07:11:23.637 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:23.637 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:23.639 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:23.639 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:23.643 27808 28994 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:23.645 27808 28994 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:23.673 27808 27808 E View    : Virtual view pointing to its host. Ignoring
09-17 07:11:23.674 27808 27851 I AssistStructure: Flattened final assist data: 1336 bytes, containing 1 windows, 17 views
09-17 07:11:23.825 27808 27808 E WebViewActivity$onCreate: onReceivedHttpError: 404 : Not Found for: https://[REDACTED_REMOTE_INSTANCE].ui.nabu.casa/unknown/webpack/runtime/async_module
09-17 07:11:23.853 27808 27808 E WebViewActivity$onCreate: onReceivedHttpError: 404 : Not Found for: https://[REDACTED_REMOTE_INSTANCE].ui.nabu.casa/unknown/node_modules/tslib/tslib.es6.mjs
09-17 07:11:25.814 27808 27808 D InsetsController: hide(ime())
09-17 07:11:25.814 27808 27808 I ImeTracker: io.homeassistant.companion.android:eea76e0b: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
09-17 07:11:25.819 27808 27808 D IntegrationRepositoryImpl: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1789623564709, currentMillis: 1789625485819)
09-17 07:11:25.827 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:25.827 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:25.828 27808 27808 D WebViewActivity: Loading HIDDEN (keepHistory true, openInApp true, serverHandleInsets false)
09-17 07:11:25.830 27808 27808 D WebViewActivity: Same base URL without meaningful path, skipping load
09-17 07:11:25.832 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:25.832 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:25.834 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:25.834 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:25.836 27808 27808 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:25.836 27808 27808 D ServerConnectionStateProviderImplKt: Using cloud / remote UI URL
09-17 07:11:32.570 27808 27808 D WebViewActivity: External bus id=6 type=config_screen/show raw=HIDDEN
09-17 07:11:32.586 27808 27808 D SensorReceiverBase: Received intent: io.homeassistant.companion.android.UPDATE_SENSORS
09-17 07:11:32.618 27808 27808 I ContentCaptureHelper: Setting logging level to OFF
09-17 07:11:32.622 27808 27808 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): android.app.Activity$$ExternalSyntheticLambda0@22ae5ef
09-17 07:11:32.622 27808 27808 D VRI[SettingsActivity]: WindowInsets changed: 1280x2856 statusBars:[0,204,0,0] navigationBars:[0,0,0,92] mandatorySystemGestures:[0,235,0,82] 
09-17 07:11:32.624 27808 27808 I Surface : Creating surface for consumer unnamed-27808-2 with slotExpansion=1 for 64 slots
09-17 07:11:32.624 27808 27808 I Surface : Creating surface for consumer VRI[SettingsActivity]#2(BLAST Consumer)2 with slotExpansion=1 for 64 slots
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.642 27808 27808 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
09-17 07:11:32.643 27808 27808 D IntegrationRepositoryImpl: setAppActive(): false
09-17 07:11:32.643 27808 27808 D IntegrationRepositoryImpl: setAppActive(): false
09-17 07:11:32.675 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.677 27808 27808 D IntegrationRepositoryImpl: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1789623564709, currentMillis: 1789625492677)
09-17 07:11:32.692 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:32.743 27808 27808 D InsetsController: hide(ime())
09-17 07:11:32.743 27808 27808 I ImeTracker: io.homeassistant.companion.android:7eb7f56c: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
09-17 07:11:32.743 27808 27808 D IntegrationRepositoryImpl: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1789623564709, currentMillis: 1789625492743)
09-17 07:11:32.744 27808 27808 D IntegrationRepositoryImpl: setAppActive(): true
09-17 07:11:33.079 27808 28994 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:33.116 27808 27808 D VRI[WebViewActivity]: visibilityChanged oldVisibility=true newVisibility=false
09-17 07:11:33.133 27808 27808 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): android.app.Activity$$ExternalSyntheticLambda0@2e94f1b
09-17 07:11:33.134 27808 27808 I AutofillManager: onInvisibleForAutofill(): expiringResponse
09-17 07:11:33.331 27808 27862 D ServerConnectionStateProviderImpl: usesInternalSsid is: false, usesWifi is: false
09-17 07:11:33.366 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.381 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.395 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.411 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.421 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.427 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.444 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.451 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.461 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.468 27808 27862 I SensorReceiverBase: Sensor updates and sync completed
09-17 07:11:33.478 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.487 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.511 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.520 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.529 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.544 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.552 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.560 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:33.569 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:34.194 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:34.221 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:34.252 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:34.271 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:34.295 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:34.313 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:34.336 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:34.356 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
09-17 07:11:34.387 27808 27808 E mpanion.android: Invalid resource ID 0x00000000.
```
