### ISSUE TITLE
Pick Media option missing from Play Media automation selection

### ISSUE THREAD

**Issue by shaggyx86** [home-assistant/frontend#19984]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I was following the Home Assistant guide to setup an automation to play a Text To Speech notification powered by Piper, and the option for "pick media" was not there. The guide referenced: https://www.home-assistant.io/voice_control/using_tts_in_automation/

After doing some research, I noticed there was an earlier issue that was marked as completed/resolved for 2024.1, but it appears that the issue may have returned for 2024.2.5. Here's the link to that issue: https://github.com/home-assistant/frontend/issues/19183

### Describe the behavior you expected

I expected the UI to give this when I selected Play Media 
![293396709-298a7903-ee17-4702-859a-73f4f2228f60](https://github.com/home-assistant/frontend/assets/4776894/655d8d77-07fa-4ce9-9bea-c4421ba9a0c0)

What I got was this, exact same as the other issue I linked to earlier
![image](https://github.com/home-assistant/frontend/assets/4776894/d2aa8a25-16f2-4482-8c84-375c833693d9)

### Steps to reproduce the issue

1.Add automation
2.In the Action/Then Do menu, click add action
3.Search for "Play Media" and click the option that shows up
![image](https://github.com/home-assistant/frontend/assets/4776894/27f936a9-3250-4401-8a51-b3ace35b1ee6)

Alternatively, the issue can be replicated by trying to follow the guide linked earlier, as the button the documentation says to click does not exist.

Frontend version is 20240207.1
...

### What version of Home Assistant Core has the issue?

2024.2.5

### In which browser are you experiencing the issue with?

Firefox 123.0

### Which operating system are you using to run this browser?

Windows 10 22H2 and Android 14 via the Companion App (version 2024.1.5-full)

**Comment by karwosts** [comment]
So admittedly I realize this is very confusing, but what I think you need to do is click Add Action, don't use the search box, scroll down to "Media player" category, click it, and then the first item in the list is "Play media". Select that, and it should have the UI you want.

**Comment by linuxrules1** [comment]
> So admittedly I realize this is very confusing, but what I think you need to do is click Add Action, don't use the search box, scroll down to "Media player" category, click it, and then the first item in the list is "Play media". Select that, and it should have the UI you want.

That worked, thanks! Not sure if this issue should be closed or left open though, since I would consider it not working via search, but working with manual scrolling to still be a bug. However, I was able to setup what I wanted to, so the overall issue is resolved.

**Comment by karwosts** [comment]
Let's leave it up for now, this remains too confusing to say it is resolved 😬

**Comment by filikun** [comment]
Oh my, why does it not show when you search? Thank you so much for this as I also struggled with finding this option and first thought is was removed.

**Comment by karwosts** [comment]
Not fixed

**Comment by bartdorsey** [comment]
I can see the pick media, but when I click it I get this empty window, despite the fact that I have a media share mounted. 
![image](https://github.com/user-attachments/assets/8f24cb99-98d5-46d5-ab10-355f0cdc56a1)

**Comment by TomKranenburg** [comment]
Pick media option is still not there. As far as I know it's also the only way to find out the media-source:// path for actions. Making this lack of functionality a bit more critical.

**Comment by berniecruz** [comment]
it works perfect now with core 2025.3.1 and MA 2.4.3.  Thanks a lot!

**Comment by lucize** [comment]
on latest 2025.7.0 and frontend 20250702.0 seems that I can't select the source anymore (ex: browse for radio), no option is shown

**Comment by karwosts** [comment]
I believe this is now resolved, play_media action was reconfigured to now always show the media selector.
