### ISSUE TITLE
Meteorologisk incorrect display

### ISSUE THREAD

**Issue by barthel-eu** [home-assistant/frontend#22765]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Inside the Android Home Assistant App. the weather forecast doesn't correctly refresh.
It breaks down to show current (only) _twice_ whereas the code is:
`type: vertical-stack
cards:
  - show_current: true
    show_forecast: true
    type: weather-forecast
    entity: weather.forecast_home_bs
    forecast_type: daily
    name: Braunschweig
  - show_current: false
    show_forecast: true
    type: weather-forecast
    entity: weather.forecast_home_bs
    forecast_type: hourly`
So if correct, the show_current should only show once.

This is on our "HA control panel", running constantly without changes. After a manual refresh, it shows the proper information.
Incorrect display: ![PXL_20241110_160343479](https://github.com/user-attachments/assets/9a281f12-fcc1-4f03-932a-f2fc51c8d69e)
After refresh: ![PXL_20241110_160355094](https://github.com/user-attachments/assets/b97d659c-3c68-4a41-adbb-53bd01e3c69e)

### Describe the behavior you expected

Showing the display shown in second image above (current, daily forecast, below hourly forcast without current). Not showing twice current only.

### Steps to reproduce the issue

1. Start the control panel.
2. Wait many hours
3. Suddenly it reduces the forecast to show_current and doesn't recover itself.

### What version of Home Assistant Core has the issue?

2024.11.1

### In which browser are you experiencing the issue with?

Fire Tablet, Home Assistant App (2024.4.1?)

### Which operating system are you using to run this browser?

Fire OS latest

### Additional information

We use a split screen with Reolink App left (to allow HA unsupported "talk"), Home Assistant App right in Kiosk mode without header (family is "users"). So manual refresh on the device is a problem. Oops. The HA App contains also a lot of controls, the weather is something the family asked for to check quickly before they leave house.
Maybe an idea to be able to click on the card to not just see the details and close that pop-up back to the corrupted forecast-display, but make sure the forecast refreshes at the same time?

**Comment by martin131** [comment]
I have similar problem on my dashboard. I am using two integrations - one for current weather and one for forecast. Sometimes the second one is not correctly displayed - it looks like `show_current` and `show_forecast` are ignored. And yes it is correct that the second integration have these values in current.  After manual refresh, It works well.

config:

```
type: custom:stack-in-card
mode: vertical
cards:
  - type: weather-forecast
    entity: weather.home
    show_current: true
    show_forecast: false
    secondary_info_attribute: wind_speed
    card_mod:
      style: |
        ha-card.regular {
          padding-bottom: 0px;
        }
  - type: weather-forecast
    show_current: false
    show_forecast: true
    forecast_type: daily
    entity: weather.forecast_home_rounded
    card_mod:
      style: |
        ha-card.regular {
          padding-top: 0px;
        }
```


before refresh:

![20241113_154014](https://github.com/user-attachments/assets/94d83a3f-85cd-4735-8794-4518200e825d)


after refresh:
![20241113_154537](https://github.com/user-attachments/assets/7ca4cf3f-195c-45e2-a24f-49175644e0ea)

**Comment by karwosts** [comment]
I think this will likely be fixed by #24188

**Comment by barthel-eu** [comment]
I worked around this by adding auto-restart every five minutes 🫣 Not perfect but ...
On the "fix" referred to yesterday, I had restarted HA this morning with core 2025.2.3 without auto-reload and it stuck again. No waiting for next core update and then retry. If still not working I'll simply reenable auto-reload 🥺🙏

**Comment by karwosts** [comment]
2025.2.3 does not include this fix. Probably check again at 2025.3.
