### ISSUE TITLE
Developer tools - State page works extremely slow

### ISSUE THREAD

**Issue by Spirituss** [home-assistant/frontend#6057]
## The problem

The page "Developer tools - State" works very slow. Page update, page scrolling, search on page - all page actions are almost unworkable, each can take up to 30 sec. 
Moreover, 'Entity' and 'States' columns of the page are very wide, while the most important column 'Attributes' which contains much more information is too narrow.

## Environment

- Home Assistant Core release with the issue: 0.110.3
- Last working Home Assistant Core release (if known): some old one (without table layout). 
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant, supervised, docker  
- Integration causing this issue: Core
- Link to integration documentation on our website: https://www.home-assistant.io/docs/tools/dev-tools/

## Problem-relevant `configuration.yaml`

```
None
```

## Traceback/Error logs

```
None
```

## Additional information
My config is quite big and contains about 1000 entities. Thus the 'States' page is rather heavy. It needs to be enhanced in terms of speed. It would be much more convenient if the columns width is reconsidered - the 'Attributes' column should be wider. It would be great to have possibility to adjust the columns width.

**Comment by Spirituss** [comment]
@Mariusthvdb, it's true, since 0.110.3 it became essentially faster, but the page still seems to be rather heavy, because browser eats almost all CPU during page scroll or update, and scrolling works rather heavily. In case the columns width are corrected, hope that the page length will become quite shorter which should enhance the situation.

**Comment by bramkragten** [comment]
The page length will not make it faster, the number of nodes on the page does.

And since this is the only page we render everything at once, it is the slowest page of our application.

**Comment by Mariusthvdb** [comment]
HI Bram,
would you be able to make the common widths adjustable? We discussed this before, but it wasn't resolved I think.

As you can see, using the current auto sizing makes the page really uncomfortable because either of the columns can be very long, and cause all others to show practically empty lines..

**Comment by bramkragten** [comment]
Please don't add feature requests and discussions to every issue, keep it on topic and create a new issue if needed.

**Comment by Mariusthvdb** [comment]
I take it you are talking to me... Sorry if it was seen as an extra feature request, I was merely trying to respond to what OP said in the first post:

> Moreover, 'Entity' and 'States' columns of the page are very wide, while the most important column 'Attributes' which contains much more information is too narrow.

Won't mention it here again, and I will try to keep the other thread alive.
My apologies again.

**Comment by Spirituss** [comment]
Hope, https://github.com/home-assistant/frontend/issues/4363#event-3379047441 is enough for this issue. Guys, thanks for fast reaction.
