### ISSUE TITLE
Translation errors for Portuguese on Integrations screen

### ISSUE THREAD

**Issue by jprates** [home-assistant/frontend#6334]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

User profile set to "Portugues" language.
[Integrations page](https://hass.ecowatt.pt/config/integrations) shows all cards with "Translation error" as the exemple below:
![image](https://user-images.githubusercontent.com/20585218/86530249-06bfaa80-beaf-11ea-854f-257a329b9b7c.png)

## Expected behavior

No localized language / translation errors should be displayed.

## Steps to reproduce

Set user language to "Portugues";
Navigate to integrations page.

## Environment

- Home Assistant release with the issue: Home Assistant 0.112.2
- Last working Home Assistant release (if known): Home Assistant 0.111.?
- Browser and browser version: Chrome 83.0.4103.116 (Official Build) (64-bit)
- Operating system: Microsoft Windows [Version 10.0.18363.900] (64-bit)

## Problem-relevant configuration

# Configure a default setup of Home Assistant (frontend, api, etc)
```
default_config:

system_health:

person:

homeassistant:
  name: (removed info)
  latitude: (removed info)
  longitude: (removed info)
  unit_system: metric
  time_zone: Europe/Lisbon
  customize:
    person.(removed info):
      entity_picture: "/local/pics/(removed info).png"
    person.(removed info):
      entity_picture: "/local/pics/(removed info).jpg"
    person.(removed info):
      entity_picture: "/local/pics/(removed info).jpg"
    person.(removed info):
      entity_picture: "/local/pics/(removed info).jpg"

weather:
  - platform: ipma

# Text to speech
tts:
  - platform: google_translate

zwave: !include zwave.yaml
automation: !include automations.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
shell_command: !include shell.yaml
zone: !include zone.yaml

google_assistant: 
  project_id: (removed info)
  service_account: !include (removed info)
  report_state: true
  exposed_domains:
    - group
  entity_config:
    group.ventila:
      name: ventilação
    group.ilumina_exterior:
      name: muro

frontend:
  themes: !include themes/ookla/ookla_theme.yaml

http: 
  ssl_certificate: /ssl/fullchain.pem 
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

```

**Comment by bramkragten** [comment]
Somebody made a mistake in the translations, this seems to be fixed now.

You can help with this yourself: <https://developers.home-assistant.io/docs/translations>

**Comment by jprates** [comment]
I have no ideia why you say "this seems to be fixed now", because I still see it exactly as it was yesterday:

![image](https://user-images.githubusercontent.com/20585218/86575619-7d23e180-bf6f-11ea-97f7-131d84d2d6fa.png)

I have enough on my hands already, I have no time nor desire to join the translation team to fix bugs.

If this is not the place to open this bug then please be so kind to redirect me to the correct place so that I can open this bug there, as this is something that needs to be fixed at the repository for everybody.

Kind regards,
-jprates

**Comment by bramkragten** [comment]
That it is fixed doesn't mean that it is already released.

And if you are too busy to fix a simple translation, why should somebody else do it for you?

**Comment by jprates** [comment]
Well I definitely didn't see that one coming.
Meeting someone so rude working on a software I love is not a nice feeling, I can tell you that.

"Fixed" not being "released" was a misunderstanding from my part, I get that, thank you for clarifying.

About your attitude:

1) I enjoy HASS a lot, I think it is a great product, so I want to help the most I can, even if by so little as report bugs;
2) I'm not a HASS programmer, I'm a rookie on HA (less than 2 months of use), so fixing the bug myself is out of question;
3) Someone has to report the bug, so that someone who knows how to fix it can do it properly and benefit all users;
4) I believe there must be more PT users out there that probably don't even know how to open a bug, so I did it;
5) "Why should somebody else do it for you" is just disrespectful, I'll take it as you having a bad day today and disregard it.

"I'm too busy" means I have a real day job that takes all of my time, plus I don't know how to do the fix or even where to look for, which increases to a large degree the workload and time I would have to spend if I was to try to fix it myself. I would probably just make it worse.

I'm a project manager, I'm not a programmer myself, so you assuming out of the blue that I don't want to fix it because I'm lazy is utterly absurd and very self centered way of thinking, sorry to say.

Congrats are due to you, and a big THANK YOU for all your contributions for HA, a great product we all love.
The same cannot be said unfortunately as for your education and politeness, you have a long way to go in that regard.

**Comment by bramkragten** [comment]
@jprates I think you are misunderstanding my point here, I was not trying to be rude.

You literally said: 

> I have enough on my hands already, I have no time nor desire to join the translation team to fix bugs.

And then you also demand a fix:

> as this is something that needs to be fixed at the repository for everybody.

Please keep in mind that most people here also have a fulltime job and are developing Home Assistant in their spare time.

I pointed you to the docs to help with the translations (no developer skills needed for that) it would be really easy to fix things there.

Your pretty harsh refusal to help with this came across as rude to all people that do help and put time into Home Assistant. (that's how it came across to me)

We always appreciate bug reports, as they are also very much needed, and I do understand you can't fix everything yourself because you don't have the skills, but this seemed like unwilling and not unable.

Maybe a language barrier or that it is written instead of spoken may lead to things being misinterpreted from both ends.

**Comment by jprates** [comment]
All clear now.

**Comment by jprates** [comment]
Just FYI

Just installed latest update, which I believe includes Update frontend to 20200702.1 #37566 and the issue is still there.
Unless the change mentioned above was not committed nor merged, the solution did not work.

![image](https://user-images.githubusercontent.com/20585218/86774483-7fa93880-c04e-11ea-8e61-9279415f98dc.png)

![image](https://user-images.githubusercontent.com/20585218/86774591-9780bc80-c04e-11ea-83f5-3ab233cd0cfa.png)

**Comment by bramkragten** [comment]
That was a patch release, not all commits are part of that.
