### ISSUE TITLE
iPhone Battery Level and State missing when charged to 100%

### ISSUE THREAD

**Issue by GirzzlyAK** [home-assistant/frontend#6355]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Related to the Mobile App Integration on default Lovelace card for iPhone Battery icons. 

I just noticed my iPhone Battery Level and State icon goes missing when my iPhone is 100% charged). The other battery indications for other battery-powered sensors, etc., are fine when at 100%, with all otherwise showing a correct icon with some percentage drained. 

Clicking on the entity, I see that the default (greyed out) icon is 'mdi:battery-100', but there IS NO 'mdi:battery-100' in the utilized MDI icon set. It is 'mdi:battery', which is used and appears fine on all of my other battery-powered sensors, like motion detectors. The default listed on those is, correctly, 'mdi:battery' when at 100%. Others have confirmed this behavior on the forum.

## Expected behavior
The battery icons for phones at 100% should be present, not missing. I assume the codes should use `mdi:battery` for the icon instead of `mdi:battery-100`.

## Steps to reproduce
Add Mobile App integration
Charge your phone to 100%
Check battery icon for both Battery Level and Battery State
Observe icon missing
Click on entity, Cog at top right, and see greyed-out `mdi:battery-100` as icon being used

## Environment

- Home Assistant release with the issue: HA: 0.111.4, Frontend: 20200603.3
- Last working Home Assistant release (if known):
- Browser and browser version: Firefox 78.0.1 (64)
- Operating system:  HassOS 4.10, aarch64 on RPi 4

## State of relevant entities
sensor.iphone...battery_level
sensor.iphone...battery_state

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by SeanPM5** [comment]
This was a problem with the iOS app, fixed here recently: https://github.com/home-assistant/iOS/issues/728

Don't think it has rolled out to a stable (app store) release yet, but the fix is in the `2020.4 (2)` testflight beta build.

**Comment by GirzzlyAK** [comment]
This occurs on my Windows desktop on Firefox on the standard entities card with various iPhone related entities listed.

**Comment by GirzzlyAK** [comment]
Think that should cover it. Thanks @SeanPM5. Will close this.

**Comment by hdaasari** [comment]
I am on version 0.112.4 and this issue still exists for android phones
