### ISSUE TITLE
Writing automations messed up 2021.5.0 

### ISSUE THREAD

**Issue by vinmar1** [home-assistant/frontend#9112]
### The problem

Writing Automations:

If I try to use action "Call service" then "light_turn_on" the form no longer comes up. I'm not sure what else is not working but this is a simple one. Since I also want to use the same motion to turn a switch on and off (call another service) using the Blueprint is a no go. I did not try to write it in yaml since it defeats the purpose of the forms.

### What is version of Home Assistant Core has the issue?

2021.5.0

### What was the last working version of Home Assistant Core?

2021.4.6

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

### Anything in the logs that might be useful for us?

```txt
No
```

**Comment by spacegaier** [comment]
The correct service name is `light.turn_on` (note the dot after the domain and before the service name). If that is only a typo in your issue description, then please provide some more details (see the issue template here in the frontend repo where I transferred your issue to). Are there any browser console errors?

**Comment by vinmar1** [comment]
That is only a typo I will try to describe better I had to uninstall due to other issues that are being addressed.
When writing a new automation and not using a blueprint, starting with empty automation.
1: Select Trigger - Works fine
2: No Condition selected - Null
3: Select Action - Call Service
4: Select Service - Light Turn On
5: At this point a form would pop up to select targets, transition, color, etc.. Instead nothing happens there is just a line with a ? link leading to documentation and you can go no further.

I'm running a clean install on a NUC and everything is up to date.

**Comment by bramkragten** [comment]
Oh... I think I see the issue now... A refresh of your browser after restarting HA should fix it...

**Comment by vinmar1** [comment]
I run the upgrade again tomorrow after I back up, just made a bunch of changes, and I'll let you know. Thanks for looking into it so quickly.

**Comment by bramkragten** [comment]
Not fixed yet, but I know the issue

**Comment by vinmar1** [comment]
I ran the update again then ran maintenance on my browser, closed and opened it again and it seems to be working again.

Not sure what you meant by not fixed yet but mine works so I'll close this.
